"""CLI entry point for the runner.

Usage:
  runner run --feature <name> [--steerable] [--preset <name>]
             [--storage-dir <path>] [--model <name>]
             [--start-phase <n>] [--no-push] [--no-fixer]
             [--max-iterations <n>]

  runner fixer --feature <name> --branch <branch> --pr <number>
               [--phase <n>] [--model <name>] [--storage-dir <path>]
               [--base-branch <branch>]
"""
from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path


# ─── run subcommand ───────────────────────────────────────────────────────────


def _cmd_run(args: argparse.Namespace) -> int:
    from runner.config import RunConfig
    from runner.phase_loop import run_phase_loop
    from runner.logging import error, log

    # Resolve storage dir
    if args.storage_dir:
        storage_dir = Path(args.storage_dir)
    else:
        # Default: ~/.conductor/projects/<repo-key>/features/<feature>
        try:
            from conductor.core.storage import StorageResolver
            resolver = StorageResolver(Path.cwd())
            storage_dir = resolver.feature_dir(args.feature)
        except Exception:
            # Fallback: cwd-relative
            storage_dir = Path.cwd() / ".conductor" / "features" / args.feature

    feature_dir = storage_dir
    config_path = feature_dir / "RUN-CONFIG.json"

    if not config_path.exists():
        error(f"RUN-CONFIG.json not found: {config_path}")
        # Write exit_code so orchestrator doesn't stall
        (feature_dir / "exit_code").write_text("1", "utf-8")
        return 1

    try:
        cfg = RunConfig.load(config_path)
    except Exception as exc:
        error(f"Failed to load RUN-CONFIG.json: {exc}")
        (feature_dir / "exit_code").write_text("1", "utf-8")
        return 1

    # CLI overrides
    if args.steerable:
        cfg.steerable = True
    if args.preset:
        cfg.preset = args.preset
    if args.model:
        cfg.model = args.model
    if args.no_fixer:
        cfg.fixer_enabled = False
    if args.quick:
        cfg.quick = True
    if args.max_iterations:
        cfg.max_iterations = args.max_iterations

    start_phase = args.start_phase or 1

    log(f"runner: feature={args.feature} start_phase={start_phase} feature_dir={feature_dir}")

    return asyncio.run(
        run_phase_loop(
            cfg=cfg,
            feature_dir=feature_dir,
            storage_dir=storage_dir,
            start_phase=start_phase,
        )
    )


# ─── fixer subcommand ─────────────────────────────────────────────────────────


def _cmd_fixer(args: argparse.Namespace) -> int:
    from runner.fixer import run_fixer, FixerConfig
    from runner.logging import error

    if args.storage_dir:
        storage_dir = Path(args.storage_dir)
    else:
        try:
            from conductor.core.storage import StorageResolver
            resolver = StorageResolver(Path.cwd())
            storage_dir = resolver.feature_dir(args.feature)
        except Exception:
            storage_dir = Path.cwd() / ".conductor" / "features" / args.feature

    project_dir = Path(args.project_dir) if args.project_dir else Path.cwd()

    cfg = FixerConfig(
        project_dir=project_dir,
        branch=args.branch,
        feature_name=args.feature,
        phase=args.phase,
        pr_number=args.pr,
        model=args.model or None,
        base_branch=args.base_branch or None,
    )

    asyncio.run(run_fixer(cfg))
    return 0


# ─── generate-run-sh subcommand ───────────────────────────────────────────────


def _cmd_generate_run_sh(args: argparse.Namespace) -> int:
    """Generate a thin run.sh that invokes the Python runner."""
    from runner.logging import log, error
    import shutil

    if args.storage_dir:
        feature_dir = Path(args.storage_dir)
    else:
        try:
            from conductor.core.storage import StorageResolver
            resolver = StorageResolver(Path.cwd())
            feature_dir = resolver.feature_dir(args.feature)
        except Exception:
            feature_dir = Path.cwd() / ".conductor" / "features" / args.feature

    feature_dir.mkdir(parents=True, exist_ok=True)

    runner_bin = shutil.which("runner") or "runner"

    run_sh_path = feature_dir / "run.sh"
    run_sh_content = f"""#!/bin/bash
# Auto-generated by `runner generate-run-sh`
# Invokes the Python runner for feature: {args.feature}
set -euo pipefail

exec {runner_bin} run --feature {args.feature} --storage-dir {feature_dir} "$@"
"""
    run_sh_path.write_text(run_sh_content, "utf-8")
    run_sh_path.chmod(0o755)
    log(f"Generated: {run_sh_path}")
    return 0


# ─── Parser ───────────────────────────────────────────────────────────────────


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="runner",
        description="Python runner — drives Claude through implementation phases",
    )
    subparsers = parser.add_subparsers(dest="subcommand", metavar="subcommand")

    # --- run ---
    p_run = subparsers.add_parser("run", help="Execute phase loop for a feature")
    p_run.add_argument("--feature", required=True, help="Feature name")
    p_run.add_argument("--steerable", action="store_true", help="Use steerable session")
    p_run.add_argument("--preset", default=None, help="Preset name (overrides RUN-CONFIG)")
    p_run.add_argument("--model", default=None, help="Model override")
    p_run.add_argument("--storage-dir", default=None, help="Feature storage directory (overrides default)")
    p_run.add_argument("--start-phase", type=int, default=None, help="Start from this phase number (1-based)")
    p_run.add_argument("--no-fixer", action="store_true", help="Disable fixer even if enabled in config")
    p_run.add_argument("--quick", action="store_true", help="Quality gate only between phases; full CI+review at end")
    p_run.add_argument("--max-iterations", type=int, default=None, help="Override max iterations per phase")

    # --- fixer ---
    p_fixer = subparsers.add_parser("fixer", help="Run PR review fixer")
    p_fixer.add_argument("--feature", required=True)
    p_fixer.add_argument("--branch", required=True)
    p_fixer.add_argument("--pr", required=True, type=int)
    p_fixer.add_argument("--phase", required=True, type=int)
    p_fixer.add_argument("--project-dir", default=None)
    p_fixer.add_argument("--model", default=None)
    p_fixer.add_argument("--storage-dir", default=None)
    p_fixer.add_argument("--base-branch", default=None)

    # --- generate-run-sh ---
    p_gen = subparsers.add_parser("generate-run-sh", help="Generate a thin run.sh for a feature")
    p_gen.add_argument("--feature", required=True)
    p_gen.add_argument("--storage-dir", default=None)

    return parser


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()

    if args.subcommand is None:
        parser.print_help()
        sys.exit(1)

    handlers = {
        "run": _cmd_run,
        "fixer": _cmd_fixer,
        "generate-run-sh": _cmd_generate_run_sh,
    }

    handler = handlers.get(args.subcommand)
    if handler is None:
        parser.error(f"Unknown subcommand: {args.subcommand}")

    exit_code = handler(args)
    sys.exit(exit_code or 0)


if __name__ == "__main__":
    main()
